### ISSUE TITLE
Address not allowed issue

### ISSUE THREAD

**Issue by CACKE** [CoolCat467/MineOS-Market-Server#20] opened 2024-08-07 22:37 UTC
![image](https://github.com/user-attachments/assets/5c723160-2635-4d77-866b-54a6c3d5e8ee)

**Comment by CoolCat467** [comment] 2024-08-07 22:52
First off, is this my re-implementation or the real server? Secondly, do you have steps to reproduce this issue?

**Comment by CACKE** [comment] 2024-08-07 22:54
your re-implementation,
1.i edited App Market lua(changed url to ip http://192.168.1.64:3004
2.i opened app market
![image](https://github.com/user-attachments/assets/940e1230-77ec-4690-9347-a3cf4ab49e9d)

**Comment by CACKE** [comment] 2024-08-07 22:56
and im doing this in ocelot emulator

**Comment by CACKE** [comment] 2024-08-07 23:08
how to fix

**Comment by CoolCat467** [comment] 2024-08-07 23:09
Let me try installing ocelot emulator and reproducing this error, currently not really sure why this is happening, message "address is not allowed" is not in my code anywhere

**Comment by CACKE** [comment] 2024-08-07 23:09
ok

**Comment by CoolCat467** [comment] 2024-08-07 23:09
Actually, could it be the emulator preventing access to address?

**Comment by CACKE** [comment] 2024-08-07 23:10
![image](https://github.com/user-attachments/assets/022b7361-4942-41c9-84f0-2a6a566077be)
i checked config

**Comment by CACKE** [comment] 2024-08-07 23:10
this is ocelot config

**Comment by CoolCat467** [comment] 2024-08-07 23:12
Try changing "deny private" to "allow private"?

**Comment by CACKE** [comment] 2024-08-07 23:14
not its not helped

**Comment by CoolCat467** [comment] 2024-08-07 23:17
Try `allow all`?

**Comment by CACKE** [comment] 2024-08-07 23:20
ok

**Comment by CACKE** [comment] 2024-08-07 23:20
![image](https://github.com/user-attachments/assets/99ee36da-bd49-44c4-80d5-7541b69dc04b)

**Comment by CACKE** [comment] 2024-08-07 23:21
not work :((((

**Comment by CACKE** [comment] 2024-08-07 23:22
so let me try on real minecraft opencomputers modpack

**Comment by CoolCat467** [comment] 2024-08-07 23:29
Can confirm, can reproduce with ocelot emulator with default settings

**Comment by CACKE** [comment] 2024-08-07 23:32
![image](https://github.com/user-attachments/assets/1ecbe2f7-5eae-46d2-8e6a-3339e8d067c8)

**Comment by CACKE** [comment] 2024-08-07 23:33
invalid address :((((

**Comment by CoolCat467** [comment] 2024-08-07 23:34
I have gotten past that error by setting ocelot config to this:
```
filteringRules: [
      "allow all"
]
```

**Comment by CACKE** [comment] 2024-08-07 23:34
okay then, but im getting error invalid adress

**Comment by CoolCat467** [comment] 2024-08-07 23:38
Yep, there is a bug you just helped me find that happens if database records don't exist

**Comment by CoolCat467** [comment] 2024-08-07 23:38
about to push a fix

**Comment by CACKE** [comment] 2024-08-07 23:41
what about youtube video guide, about how to host this?

**Comment by CoolCat467** [comment] 2024-08-07 23:42
I could potentially do that, but what you have done here is the right way to go about it.

**Comment by CoolCat467** [comment] 2024-08-07 23:42
I should add more information about how to get this running in the README file

**Comment by CoolCat467** [comment] 2024-08-07 23:43
Anyways, if you re-run the installation command
```
pip install git+https://github.com/CoolCat467/MineOS-Market-Server.git
```
it will install the updated version

**Comment by CACKE** [comment] 2024-08-07 23:44
okay, and the last question
Do i need to put in App Market lua the http://ip:2222 or http://ip:2222/MineOSAPI/2.04/

**Comment by CoolCat467** [comment] 2024-08-07 23:45
`http://ip:2222/MineOSAPI/2.04/` I believe, one sec

**Comment by CACKE** [comment] 2024-08-07 23:47
![image](https://github.com/user-attachments/assets/fcb7e267-3030-4e21-a8a5-863c33136943)
![image](https://github.com/user-attachments/assets/87f05037-f25f-4a36-a576-d180bd4271e4)
![image](https://github.com/user-attachments/assets/4291f87f-09f5-43e7-af7b-5fc8e26514ac)

**Comment by CoolCat467** [comment] 2024-08-07 23:48
And as you may have already found, there is a debug page you can access through the web-browser if you go to http://192.168.1.64:2222/ in your case

**Comment by CACKE** [comment] 2024-08-07 23:48
![image](https://github.com/user-attachments/assets/ea33d2bf-b50b-4f5f-8cfc-579e1c458473)

**Comment by CoolCat467** [comment] 2024-08-07 23:48
Interesting...

**Comment by CACKE** [comment] 2024-08-07 23:48
![image](https://github.com/user-attachments/assets/716de7d3-6ba3-46c7-8128-19adf98417a7)

**Comment by CoolCat467** [comment] 2024-08-07 23:49
Ok let me try a clean installation of the server myself really quick

**Comment by CACKE** [comment] 2024-08-07 23:49
okay, anyways, thanks for creating this!

**Comment by CoolCat467** [comment] 2024-08-07 23:51
Making sure, the ocelot configuration file you are editing is indeed the one being used by the emulator?

**Comment by CACKE** [comment] 2024-08-07 23:56
one sec

**Comment by CACKE** [comment] 2024-08-07 23:57
![image](https://github.com/user-attachments/assets/399d8c58-7c61-4e3d-91ec-22ea4e19f6a2)

**Comment by CACKE** [comment] 2024-08-07 23:57
PROGRESS

**Comment by CACKE** [comment] 2024-08-07 23:57
![image](https://github.com/user-attachments/assets/5d595112-9931-4d8f-83f0-c90a06c45c3e)

**Comment by CoolCat467** [comment] 2024-08-07 23:59
Yep, that's the issue I just fixed a little bit ago with if it's the first time running and the database files don't exist, it used to crash. Fixed in most recent update.

**Comment by CACKE** [comment] 2024-08-07 23:59
do i need to update?

**Comment by CoolCat467** [comment] 2024-08-08 00:00
Yes, reinstall the server with the installation command again:
```
pip install git+https://github.com/CoolCat467/MineOS-Market-Server.git
```

**Comment by CACKE** [comment] 2024-08-08 00:01
![image](https://github.com/user-attachments/assets/81790b5d-630e-43e5-b61a-51836fa6373b)
oh, thanks!!!!!!!

**Comment by CACKE** [comment] 2024-08-08 00:02
![image](https://github.com/user-attachments/assets/c2df9d76-6694-4eeb-a721-7eb09012f3e4)

**Comment by CACKE** [comment] 2024-08-08 00:02
![image](https://github.com/user-attachments/assets/25902ad4-e2fa-4514-8489-e99f837e3709)

**Comment by CACKE** [comment] 2024-08-08 00:03
![image](https://github.com/user-attachments/assets/3399f12c-6f5b-4dc4-af38-c89d7bde0e50)
LOL

**Comment by CoolCat467** [comment] 2024-08-08 00:04
yooo

**Comment by CACKE** [comment] 2024-08-08 00:05
email not delivering to my email :(((

**Comment by CACKE** [comment] 2024-08-08 00:07
i mean account activation email

**Comment by CACKE** [comment] 2024-08-08 00:07
![image](https://github.com/user-attachments/assets/629156e6-d989-4924-aabc-451891d9339a)
LOL

**Comment by CACKE** [comment] 2024-08-08 00:07
email send to console

**Comment by CoolCat467** [comment] 2024-08-08 00:09
Yes, that is intended

**Comment by CACKE** [comment] 2024-08-08 00:09
oh, thats cool, let me try to publish some apps

**Comment by CoolCat467** [comment] 2024-08-08 00:10
The important thing is that token in the console email. Go to website it wants you to go to and you should be verified

**Comment by CoolCat467** [comment] 2024-08-08 00:10
I will warn, publication publishing is most sketchy and probably bug-prone part, very complex and testing against real server would be spam so I've made a lot of guesses

**Comment by CACKE** [comment] 2024-08-08 00:12
![image](https://github.com/user-attachments/assets/b6859bd0-2175-4760-aea6-c3be88c75858)

**Comment by CoolCat467** [comment] 2024-08-08 00:12
Eating supper, will be back soon

**Comment by CACKE** [comment] 2024-08-08 00:13
i see messages also not work
Bon appetit

**Comment by CoolCat467** [comment] 2024-08-08 01:15
Back and pushed an update again, there was a major issue in the way the server was processing when the client sends lists of file ids over

**Comment by CACKE** [comment] 2024-08-08 01:17
soo i need to update?

**Comment by CACKE** [comment] 2024-08-08 01:17
![image](https://github.com/user-attachments/assets/34ded609-7d8f-4e3b-a3b0-8f24536e0340)
lol

**Comment by CoolCat467** [comment] 2024-08-08 01:18
> soo i need to update?

Yes

**Comment by CoolCat467** [comment] 2024-08-08 01:18
At least for wallpaper publication upload test, seems to be working

**Comment by CACKE** [comment] 2024-08-08 01:21
ok

**Comment by CACKE** [comment] 2024-08-08 01:22
![image](https://github.com/user-attachments/assets/00e66f0e-9ca2-4bd0-8623-ebbc4e99bffc)
not work

**Comment by CACKE** [comment] 2024-08-08 01:23
also settings not working

**Comment by CoolCat467** [comment] 2024-08-08 01:24
Response code 400 shouldn't happen anymore, that means the server instance that is running is outdated

**Comment by CoolCat467** [comment] 2024-08-08 01:24
Every time you update you also have to stop and restart the market server

**Comment by CACKE** [comment] 2024-08-08 01:24
ok

**Comment by CACKE** [comment] 2024-08-08 01:27
![image](https://github.com/user-attachments/assets/ec87c0ed-f976-4975-8ca1-5a7d9807aec4)
not work anyways

**Comment by CoolCat467** [comment] 2024-08-08 01:32
Maybe didn't reinstall package because version was still the same, so I just bumped the project version to v1.0.2. Hopefully if you reinstall again this should be fixed, or at least give a better error message now.

**Comment by CACKE** [comment] 2024-08-08 01:34
ok

**Comment by CACKE** [comment] 2024-08-08 01:36
![image](https://github.com/user-attachments/assets/cb222d1b-ffa0-4425-858f-9621c80baff5)

**Comment by CACKE** [comment] 2024-08-08 01:36
![image](https://github.com/user-attachments/assets/ffd2d228-1268-4b1d-870f-77aaad2e0ccf)

**Comment by CACKE** [comment] 2024-08-08 01:38
settings now works

**Comment by CoolCat467** [comment] 2024-08-08 01:40
Ah, another issue of what happens if there is an empty publications database. One sec, almost done fixing.

**Comment by CACKE** [comment] 2024-08-08 01:40
okay, also chat now works

**Comment by CoolCat467** [comment] 2024-08-08 01:42
Ok, update pushed, reinstall with
```
pip install git+https://github.com/CoolCat467/MineOS-Market-Server.git --force-reinstall
```
and restart server

**Comment by CACKE** [comment] 2024-08-08 01:43
ok

**Comment by CACKE** [comment] 2024-08-08 01:47
works, but crashing when opening app info

**Comment by CACKE** [comment] 2024-08-08 01:48
![image](https://github.com/user-attachments/assets/cda1fa05-d298-499b-9c22-9d2f58dd5f3a)

**Comment by CoolCat467** [comment] 2024-08-08 01:49
Basically server is sending back a empty value, because no publications exist. Trying to figure out how to fix.

**Comment by CACKE** [comment] 2024-08-08 01:50
okay

**Comment by CACKE** [comment] 2024-08-08 01:55
apps publish works

**Comment by CACKE** [comment] 2024-08-08 01:55
but icon not displays

**Comment by CoolCat467** [comment] 2024-08-08 01:58
Basically issue is app market client does unchecked request for applications, and this is a bug in the client itself. I could fix it with a hack, but best solution is probably to create an application publication. Really though, I need to report this issue to official MineOS repo.

**Comment by CoolCat467** [comment] 2024-08-08 02:00
Basically app market tries to get top 15 most popular publications and show their icons moving around, and when it does that request it doesn't properly handle the case of 0 and/or <15 publications being published.

**Comment by CACKE** [comment] 2024-08-08 02:10
![image](https://github.com/user-attachments/assets/b4cbc5c9-c5fc-44e1-bba2-222a8732cbf4)
sooooo

**Comment by CoolCat467** [comment] 2024-08-08 02:11
Actually might have found it, errors whenever applications are missing `icon_url`. Probably a bug on my end, working on finding it.

**Comment by CACKE** [comment] 2024-08-08 02:13
wtf, i created 13 apps, and new apps doesnt appears

**Comment by CACKE** [comment] 2024-08-08 02:14
![image](https://github.com/user-attachments/assets/0511e926-9c44-49fe-83da-327b709eae78)

**Comment by CACKE** [comment] 2024-08-08 02:15
1 wallpaper and 17 apps

**Comment by CoolCat467** [comment] 2024-08-08 02:15
Depends on what category applications were submitted to

**Comment by CACKE** [comment] 2024-08-08 02:15
apps

**Comment by CoolCat467** [comment] 2024-08-08 02:16
Go to debug page in web browser and enter `publications` for `Script Name` and press `Post`

**Comment by CACKE** [comment] 2024-08-08 02:16
ok

**Comment by CACKE** [comment] 2024-08-08 02:18
`  {success=true,result={{file_id=18,publication_name='ooo',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=17,publication_name='ccc',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=16,publication_name='vv',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=15,publication_name='ввв',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=14,publication_name='gg11',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=1,popularity=0.0},{file_id=13,publication_name='dd',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=1,popularity=0.0},{file_id=12,publication_name='ddddd',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=11,publication_name='3131313',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=10,publication_name='rr',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=9,publication_name='vassada',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=8,publication_name='hh',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=7,publication_name='gg',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=6,publication_name='not a test',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=5,publication_name='213312132',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=4,publication_name='12',user_name='eblan',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=3,publication_name='ee',user_name='sasihuy',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=2,publication_name='TESY',user_name='sasihuy',version=1.0,category_id=1,reviews_count=0,downloads=0,popularity=0.0},{file_id=1,publication_name='TEST',user_name='sasihuy',version=1.0,category_id=4,reviews_count=0,downloads=1,popularity=0.0}}}
`

**Comment by CACKE** [comment] 2024-08-08 02:22
Also don't worry about usernames, it's just random words

чт, 8 авг. 2024 г., 05:16 CoolCat467 ***@***.***>:

**Comment by CoolCat467** [comment] 2024-08-08 03:46
https://github.com/IgorTimofeev/MineOS/pull/629 is fixing this issue

**Comment by CACKE** [comment] 2024-08-08 03:54
Okay then, anyways, thanks for making this!

чт, 8 авг. 2024 г., 06:46 CoolCat467 ***@***.***>:

**Comment by CoolCat467** [comment] 2024-08-08 17:47
Will do more extensive testing with official app market application later. Thank you for informing me about that ocelot emulator, that will be incredibly helpful during testing!

**Comment by CoolCat467** [comment] 2024-08-08 17:52
> ![image](https://private-user-images.githubusercontent.com/89192120/356051874-cda1fa05-d298-499b-9c22-9d2f58dd5f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzgzMjIsIm5iZiI6MTcyMzEzODAyMiwicGF0aCI6Ii84OTE5MjEyMC8zNTYwNTE4NzQtY2RhMWZhMDUtZDI5OC00OTliLTljMjItOWQyZjU4ZGQ1ZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE3MjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzODdkZTdhYjljYTExZTE5NDgwOWI4Y2MyOTY5Nzk3ODBmM2U4M2MwZmYwYjhjMjMzZmY5NWEyN2Y5NjdiZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oOQnuQbuBWP6V8F9_6gHgu5LOu9WmiVujYrZXQyaqvQ)

Fixed at least part of that, statistics page was sending back invalid data, and if https://github.com/IgorTimofeev/MineOS/pull/630 gets merged it should allow app market to handle the case where no publications exist without crashing

**Comment by CACKE** [comment] 2024-08-08 17:52
Thanks for you for making this market server

**Comment by CoolCat467** [comment] 2024-08-13 23:08
Updates, basically they've rejected my pull requests for fixing the error case of if there are no publications. I might implement setting up a default application for a custom installation of the app market, but I'd have to do some additional work for users being able to change the api endpoint to that their own selection.

**Comment by CoolCat467** [comment] 2024-08-14 04:52
@CACKE With latest updates, I believe I have fixed application uploading! If you still encounter issues, please open another issue.

**Closed by CoolCat467** 2024-08-14 04:52 UTC

**Comment by CoolCat467** [comment] 2024-08-20 04:41
I've added a [backup of the official publications as of 2024-08-13](https://github.com/CoolCat467/MineOS-Market-Server/blob/main/backup/publications.json) and instructions in the README about how import them.
