### ISSUE TITLE
Address is not allowed issue

### ISSUE THREAD

**Issue by Bufka2011** [CoolCat467/MineOS-Market-Server#23] opened 2024-08-20 03:22 UTC
I installed and ran the program, but it doesn't work.

![image](https://github.com/user-attachments/assets/ed21e344-230c-456d-be15-be405d49a5bc)

I changed the address from

local host = "http://mineos.buttex.ru/MineOSAPI/2.04/"

To

local host = "http://here_is_my_IP:3004/MineOSAPI/2.04/"

**Comment by CoolCat467** [comment] 2024-08-20 03:29
Duplicate of https://github.com/CoolCat467/MineOS-Market-Server/issues/20, if you are using the Ocelot Emulator, you need to change `deny private` to `allow private` around line 1000 in your `opencomputers.conf` file

**Comment by Bufka2011** [comment] 2024-08-20 03:30
I am in Minecraft.

**Comment by CoolCat467** [comment] 2024-08-20 03:31
Same issue for actual minecraft instance, need to go to `opencomputers.conf` and change `deny private` to `allow private`

**Comment by CoolCat467** [comment] 2024-08-20 03:32
Thank you for reminding me, I need to add this to the README file

**Comment by Bufka2011** [comment] 2024-08-20 03:33
Thank you for help

**Comment by Bufka2011** [comment] 2024-08-20 03:34
But where is it?

**Comment by Bufka2011** [comment] 2024-08-20 03:34
I can't find it in .minecraft/config

**Comment by CoolCat467** [comment] 2024-08-20 03:35
Good question, let me do a search

**Comment by CoolCat467** [comment] 2024-08-20 03:37
Supposedly might be in `.minecraft/config/opencomputers` folder?

**Comment by Bufka2011** [comment] 2024-08-20 03:38
![image](https://github.com/user-attachments/assets/f3433be5-8d13-4b35-89ef-c425ae488d37)
Ummmm...

**Comment by CoolCat467** [comment] 2024-08-20 03:38
Look in `settings.conf`

**Comment by Bufka2011** [comment] 2024-08-20 03:40
Nothing...

I found it!
![image](https://github.com/user-attachments/assets/4eb4ef30-5f47-432c-b0eb-505f3bfdac3f)

I think this should be documented in the readme.

**Comment by CoolCat467** [comment] 2024-08-20 03:41
Yep, will be adding that shortly. Thank you for your feedback!

**Comment by Bufka2011** [comment] 2024-08-20 03:41
Thank you for your help!

**Closed** 2024-08-20 03:41 UTC

**Comment by CoolCat467** [comment] 2024-08-20 04:40
Oh yea by the way, I've added a [backup of the official publications as of 2024-08-13](https://github.com/CoolCat467/MineOS-Market-Server/blob/main/backup/publications.json) and instructions about how import them.
